language: node_js

node_js:
  - "7.9.0"

branches:
  only:
  - master

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - cd App/
  - npm install -g cnpm --registry=https://registry.npm.taobao.org 
  - cnpm install node-sass
  - cnpm install

script:
  - npm run build

sudo: false
